// Generate the MoonBit data files the site is compiled with:
//   ui/data.mbt      benchmark rows + plugin list   (from app/website/data.json, written by packages/compare/collect.mjs)
//   ui/samples.mbt   curated sample SVGs (testdata + compare corpus), optimized live in the browser
//   ui/api_data.mbt  the public API                 (from `MOON_WORK=off moon -C svgo doc` → svgo/_build/doc)
//   ui/cli_data.mbt  CLI flag table                 (parsed from the USAGE constant in app/cli/main.mbt)
// Usage: node app/website/gen.mjs   (run by app/website/build.mjs)
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = new URL("../..", import.meta.url).pathname;
const UI = join(ROOT, "app/website/ui");
const HEADER = "// Generated by app/website/gen.mjs. DO NOT EDIT.\n";

// MoonBit string literal (double quoted, escapes handled)
const str = (s) => JSON.stringify(String(s)).replace(/\\u2028/g, " ").replace(/\\u2029/g, " ");
const num = (n) => (Number.isInteger(n) ? String(n) : String(n).includes("e") ? Number(n).toFixed(6) : String(n));
const dbl = (n) => { const s = num(n); return s.includes(".") ? s : s + ".0"; };

// ---------- data.mbt ----------
const data = JSON.parse(readFileSync(join(ROOT, "app/website/data.json"), "utf8"));
writeFileSync(join(UI, "data.mbt"), `${HEADER}
///|
pub let generated_on : String = ${str(data.generated)}

///|
pub let svgo_js_version : String = ${str(data.svgoVersion)}

///|
pub let wasm_bytes : Int = ${data.wasmBytes}

///|
/// One corpus file: bytes before, after svgo.mbt and after svgo-js, plus
/// same-process milliseconds per call for both.
pub let bench_rows : Array[BenchRow] = [
${data.rows.map((r) => `  { file: ${str(r.file)}, original: ${r.original}, mbt: ${r.mbt}, js: ${r.js}, mbt_ms: ${dbl(r.mbtMs)}, js_ms: ${dbl(r.jsMs)} },`).join("\n")}
]
`);

// ---------- samples.mbt ----------
// Curated: one real editor export (the default in the playground) plus the
// classic large test files, which make a better gallery than icons do.
const SAMPLES = [
  ["Sketch icon", "svgo/testdata/sketch-icon.svg"],
  ["SVG logo", "packages/compare/corpus/SVG_logo.svg"],
  ["Python logo", "packages/compare/corpus/Python_logo_and_wordmark.svg"],
  ["Tux", "packages/compare/corpus/Tux.svg"],
  ["Ghostscript Tiger", "packages/compare/corpus/Ghostscript_Tiger.svg"],
  ["World map", "packages/compare/corpus/World_map_-_low_resolution.svg"],
];
writeFileSync(join(UI, "samples.mbt"), `${HEADER}
///|
/// Sample documents bundled with the site: shown in the gallery, selectable
/// in the playground, optimized live in the browser.
pub let samples : Array[Sample] = [
${SAMPLES.map(([name, f]) => `  { name: ${str(name)}, file: ${str(f.split("/").pop())}, svg: ${str(readFileSync(join(ROOT, f), "utf8"))} },`).join("\n")}
]
`);

// ---------- api_data.mbt ----------
// `moon doc` must run with workspace mode off (the app member only builds
// for js): `MOON_WORK=off moon -C svgo doc` writes svgo/_build/doc. The old
// workspace location is still accepted.
const DOC = ["svgo/_build/doc/perfectpan/svgo", "_build/doc/perfectpan/svgo"].map((d) => join(ROOT, d)).find(existsSync);
function findPackages(dir, rel = "") {
  const out = [];
  if (existsSync(join(dir, "package_data.json"))) out.push({ dir, rel });
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) out.push(...findPackages(join(dir, e.name), rel ? `${rel}/${e.name}` : e.name));
  }
  return out;
}
const ORDER = ["", "xml", "path", "plugins", "wasm"];
const plain = (html) => html.replace(/<a href="[^"]*">([^<]*)<\/a>/g, "$1").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
const pkgs = DOC ? findPackages(DOC).filter((p) => ORDER.includes(p.rel)).sort((a, b) => ORDER.indexOf(a.rel) - ORDER.indexOf(b.rel)) : [];
if (pkgs.length === 0) console.warn("app/website/gen.mjs: no moon doc output found; run `MOON_WORK=off moon -C svgo doc` (keeping the committed api_data.mbt)");
else {
  const packages = pkgs.map(({ dir, rel }) => {
    const d = JSON.parse(readFileSync(join(dir, "package_data.json"), "utf8"));
    const items = [];
    for (const [kind, list] of [["type", d.types], ["error", d.errors], ["trait", d.traits], ["fn", d.values]]) {
      for (const m of list || []) {
        items.push({
          kind, name: m.name, signature: plain(m.signature), doc: m.docstring || "",
          file: m.loc ? `${m.loc.file}#L${m.loc.line}` : "",
          methods: (m.methods || []).map((f) => ({ name: f.name, signature: plain(f.signature), doc: f.docstring || "" })),
          impls: (m.impls || []).map((i) => i.trait.name),
        });
      }
    }
    return { path: rel ? `perfectpan/svgo/${rel}` : "perfectpan/svgo", alias: rel ? `@${rel.split("/").pop()}` : "@svgo", items };
  });
  writeFileSync(join(UI, "api_data.mbt"), `${HEADER}
///|
/// The public API, extracted from \`moon doc\` output.
pub let api_packages : Array[ApiPackage] = [
${packages.map((p) => `  {
    path: ${str(p.path)},
    short: ${str(p.alias)},
    items: [
${p.items.map((it) => `      {
        kind: ${str(it.kind)},
        name: ${str(it.name)},
        signature: ${str(it.signature)},
        doc: ${str(it.doc)},
        file: ${str(it.file)},
        methods: [${it.methods.map((m) => `{ name: ${str(m.name)}, signature: ${str(m.signature)}, doc: ${str(m.doc)} }`).join(", ")}],
        impls: [${it.impls.map(str).join(", ")}],
      },`).join("\n")}
    ],
  },`).join("\n")}
]
`);
}
console.log(`app/website/gen.mjs: data (${data.rows.length} rows), samples (${SAMPLES.length}), api (${pkgs.length} packages)`);

// ---------- cli_data.mbt ----------
// Parse the option lines out of the CLI's USAGE constant so the site's flag
// table always matches the binary. The USAGE string uses MoonBit's `#|` line
// prefix; we strip that, find the block between "options:" and "exit codes:",
// and turn each option line into { flag, description }. Continuation lines
// (indented past the flag column) are joined onto the previous description.
const cliMain = readFileSync(join(ROOT, "app/cli/main.mbt"), "utf8");
const usageLines = [];
let inUsage = false;
for (const line of cliMain.split("\n")) {
  if (line.match(/^\s*const USAGE\s*=/)) { inUsage = true; continue; }
  if (inUsage) {
    const m = line.match(/^\s*#\|(.*)$/);
    if (m) { usageLines.push(m[1]); }
    else if (line.trim() === "") {
      // blank line inside the string literal is just an empty #| line; skip
      // unless we've already seen content (the literal ends at the first
      // non-#|, non-blank line after content).
      if (usageLines.length > 0) { /* keep going, blank lines are part of it */ }
    } else {
      break; // end of the string literal
    }
  }
}
const usage = usageLines.join("\n");
const optMatch = usage.match(/options:\n([\s\S]*?)\nexit codes:/);
const cliFlags = [];
if (optMatch) {
  const block = optMatch[1];
  for (const raw of block.split("\n")) {
    const line = raw.replace(/\s+$/, "");
    if (line.trim() === "") continue;
    // An option line starts with a dash after the leading indent.
    const isOption = /^\s+-/.test(line);
    if (isOption) {
      // Split on the first run of 2+ spaces: left = flag(s), right = description.
      const split = line.match(/^(\s+-\S.*?)\s{2,}(.*)$/);
      if (split) {
        cliFlags.push({ flag: split[1].trim(), description: split[2].trim() });
      } else {
        cliFlags.push({ flag: line.trim(), description: "" });
      }
    } else if (cliFlags.length > 0) {
      // Continuation: append to the previous description.
      const prev = cliFlags[cliFlags.length - 1];
      prev.description = prev.description
        ? `${prev.description} ${line.trim()}`
        : line.trim();
    }
  }
} else {
  console.warn("app/website/gen.mjs: could not find options block in app/cli/main.mbt");
}
writeFileSync(join(UI, "cli_data.mbt"), `${HEADER}
///|
/// Command-line flags, parsed from the USAGE constant in app/cli/main.mbt.
/// Each entry is the flag string (e.g. "-o, --output <file>") and its
/// one-line description. Add a flag to the CLI and it shows up here on the
/// next build.
pub let cli_flags : Array[CliFlag] = [
${cliFlags.map((f) => `  { flag: ${str(f.flag)}, description: ${str(f.description)} },`).join("\n")}
]
`);
console.log(`app/website/gen.mjs: cli (${cliFlags.length} flags)`);

// The generated .mbt files must pass `moon fmt --check`. Run the formatter
// on them so gen.mjs is re-runnable without hand edits afterwards.
spawnSync("moon", ["fmt", join(UI, "data.mbt"), join(UI, "samples.mbt"), join(UI, "api_data.mbt"), join(UI, "cli_data.mbt")], { stdio: "inherit" });
