// Generate the MoonBit data files the site is compiled with:
//   ui/data.mbt      benchmark rows + plugin list   (from app/data.json, written by packages/compare/collect.mjs)
//   ui/samples.mbt   curated sample SVGs (testdata + compare corpus), optimized live in the browser
//   ui/api_data.mbt  the public API                 (from `MOON_WORK=off moon -C svgo doc` → svgo/_build/doc)
// Usage: node app/gen.mjs   (run by app/build.mjs)
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const UI = join(ROOT, "app/ui");
const HEADER = "// Generated by app/gen.mjs. DO NOT EDIT.\n";

// MoonBit string literal (double quoted, escapes handled)
const str = (s) => JSON.stringify(String(s)).replace(/\\u2028/g, " ").replace(/\\u2029/g, " ");
const num = (n) => (Number.isInteger(n) ? String(n) : String(n).includes("e") ? Number(n).toFixed(6) : String(n));
const dbl = (n) => { const s = num(n); return s.includes(".") ? s : s + ".0"; };

// ---------- data.mbt ----------
const data = JSON.parse(readFileSync(join(ROOT, "app/data.json"), "utf8"));
writeFileSync(join(UI, "data.mbt"), `${HEADER}
///|
pub let generated_on : String = ${str(data.generated)}

///|
pub let svgo_js_version : String = ${str(data.svgoVersion)}

///|
pub let wasm_bytes : Int = ${data.wasmBytes}

///|
/// One corpus file: bytes before, after svgo.mbt and after svgo-js, plus
/// same-process milliseconds per call for both.
pub let bench_rows : Array[BenchRow] = [
${data.rows.map((r) => `  { file: ${str(r.file)}, original: ${r.original}, mbt: ${r.mbt}, js: ${r.js}, mbt_ms: ${dbl(r.mbtMs)}, js_ms: ${dbl(r.jsMs)} },`).join("\n")}
]
`);

// ---------- samples.mbt ----------
// Curated: one real editor export (the default in the playground) plus the
// classic large test files, which make a better gallery than icons do.
const SAMPLES = [
  ["Sketch icon", "svgo/testdata/sketch-icon.svg"],
  ["SVG logo", "packages/compare/corpus/SVG_logo.svg"],
  ["Python logo", "packages/compare/corpus/Python_logo_and_wordmark.svg"],
  ["Tux", "packages/compare/corpus/Tux.svg"],
  ["Ghostscript Tiger", "packages/compare/corpus/Ghostscript_Tiger.svg"],
  ["World map", "packages/compare/corpus/World_map_-_low_resolution.svg"],
];
writeFileSync(join(UI, "samples.mbt"), `${HEADER}
///|
/// Sample documents bundled with the site: shown in the gallery, selectable
/// in the playground, optimized live in the browser.
pub let samples : Array[Sample] = [
${SAMPLES.map(([name, f]) => `  { name: ${str(name)}, file: ${str(f.split("/").pop())}, svg: ${str(readFileSync(join(ROOT, f), "utf8"))} },`).join("\n")}
]
`);

// ---------- api_data.mbt ----------
// `moon doc` must run with workspace mode off (the app member only builds
// for js): `MOON_WORK=off moon -C svgo doc` writes svgo/_build/doc. The old
// workspace location is still accepted.
const DOC = ["svgo/_build/doc/perfectpan/svgo", "_build/doc/perfectpan/svgo"].map((d) => join(ROOT, d)).find(existsSync);
function findPackages(dir, rel = "") {
  const out = [];
  if (existsSync(join(dir, "package_data.json"))) out.push({ dir, rel });
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) out.push(...findPackages(join(dir, e.name), rel ? `${rel}/${e.name}` : e.name));
  }
  return out;
}
const ORDER = ["", "xml", "path", "plugins", "wasm"];
const plain = (html) => html.replace(/<a href="[^"]*">([^<]*)<\/a>/g, "$1").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
const pkgs = DOC ? findPackages(DOC).filter((p) => ORDER.includes(p.rel)).sort((a, b) => ORDER.indexOf(a.rel) - ORDER.indexOf(b.rel)) : [];
if (pkgs.length === 0) console.warn("app/gen.mjs: no moon doc output found; run `MOON_WORK=off moon -C svgo doc` (keeping the committed api_data.mbt)");
else {
  const packages = pkgs.map(({ dir, rel }) => {
    const d = JSON.parse(readFileSync(join(dir, "package_data.json"), "utf8"));
    const items = [];
    for (const [kind, list] of [["type", d.types], ["error", d.errors], ["trait", d.traits], ["fn", d.values]]) {
      for (const m of list || []) {
        items.push({
          kind, name: m.name, signature: plain(m.signature), doc: m.docstring || "",
          file: m.loc ? `${m.loc.file}#L${m.loc.line}` : "",
          methods: (m.methods || []).map((f) => ({ name: f.name, signature: plain(f.signature), doc: f.docstring || "" })),
          impls: (m.impls || []).map((i) => i.trait.name),
        });
      }
    }
    return { path: rel ? `perfectpan/svgo/${rel}` : "perfectpan/svgo", alias: rel ? `@${rel.split("/").pop()}` : "@svgo", items };
  });
  writeFileSync(join(UI, "api_data.mbt"), `${HEADER}
///|
/// The public API, extracted from \`moon doc\` output.
pub let api_packages : Array[ApiPackage] = [
${packages.map((p) => `  {
    path: ${str(p.path)},
    short: ${str(p.alias)},
    items: [
${p.items.map((it) => `      {
        kind: ${str(it.kind)},
        name: ${str(it.name)},
        signature: ${str(it.signature)},
        doc: ${str(it.doc)},
        file: ${str(it.file)},
        methods: [${it.methods.map((m) => `{ name: ${str(m.name)}, signature: ${str(m.signature)}, doc: ${str(m.doc)} }`).join(", ")}],
        impls: [${it.impls.map(str).join(", ")}],
      },`).join("\n")}
    ],
  },`).join("\n")}
]
`);
}
console.log(`app/gen.mjs: data (${data.rows.length} rows), samples (${SAMPLES.length}), api (${pkgs.length} packages)`);
