#!/usr/bin/env python3
"""Turn plugins/fixtures/*.txt into plugins/fixtures_test.mbt.

Fixture format (the same layout as svgo's plugin tests):

    <svg ...>input</svg>

    @@@

    <svg ...>expected output</svg>

    @@@

    {"precision": 2, "multipass": true}      # optional third section

The file name is `<pluginName>.<nn>.txt`; only that plugin runs, once
(or until it stops changing the tree with "multipass": true). Whitespace
between tags is ignored when comparing, so fixtures can be indented.

    python3 scripts/gen-fixtures.py           # write plugins/fixtures_test.mbt
    python3 scripts/gen-fixtures.py --check   # exit 1 if the file is stale
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "plugins" / "fixtures"
OUT = ROOT / "plugins" / "fixtures_test.mbt"


def multiline(text: str) -> str:
    lines = text.strip("\n").split("\n")
    return "(\n" + "\n".join("      #|" + l for l in lines) + "\n    )"


def render() -> str:
    parts = [
        "// Generated by scripts/gen-fixtures.py from plugins/fixtures/*.txt. DO NOT EDIT.",
        "// Regenerate with: python3 scripts/gen-fixtures.py",
    ]
    for path in sorted(FIXTURES.glob("*.txt")):
        plugin = path.name.split(".")[0]
        sections = [s.strip("\n") for s in path.read_text().split("\n@@@\n")]
        if len(sections) < 2:
            sys.exit(f"{path}: expected 'input @@@ expected'")
        params = json.loads(sections[2]) if len(sections) > 2 and sections[2].strip() else {}
        precision = int(params.get("precision", 3))
        multipass = "true" if params.get("multipass", False) else "false"
        parts.append(
            f'''
///|
test "fixture {path.stem}" {{
  check_fixture(
    "{plugin}",
    {multiline(sections[0])},
    {multiline(sections[1])},
    precision={precision},
    multipass={multipass},
  )
}}'''
        )
    return "\n".join(parts) + "\n"


def main() -> None:
    content = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale; run python3 scripts/gen-fixtures.py")
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return
    OUT.write_text(content)
    n = len(list(FIXTURES.glob("*.txt")))
    print(f"wrote {OUT.relative_to(ROOT)} ({n} fixtures)")


if __name__ == "__main__":
    main()
