#!/usr/bin/env python3
"""Turn plugin fixtures into svgo/plugins/fixtures_test.mbt.

Two sources:

  svgo/plugins/fixtures/*.txt            our own cases
  svgo/plugins/fixtures/upstream/*.txt   svgo's test/plugins suite, verbatim (see NOTICE.md)

Both use svgo's layout; upstream files may start with a description block:

    Removes empty attributes            # optional, upstream only

    ===

    <svg ...>input</svg>

    @@@

    <svg ...>expected output</svg>

    @@@

    {"floatPrecision": 2}               # optional params

The file name is `<pluginName>.<nn>.txt`; only that plugin runs. Our own cases
run once, or until the tree stops changing with `{"multipass": true}`.
Upstream cases follow svgo's runner: the plugin runs twice and the tree must
equal `expected` after each run (once for convertTransform, like upstream).
Whitespace between tags is ignored when comparing.

Upstream params are passed through as JSON; `floatPrecision` also sets precision. Cases listed in
fixtures/upstream/KNOWN_FAILURES.txt are generated as expected failures: the
test fails if the case starts passing, so a fix must also delete the line.
Cases for the preset plugins svgo.mbt has not written yet are generated as
skipped tests (see NOT_IMPLEMENTED below).

    python3 scripts/gen-fixtures.py           # write svgo/plugins/fixtures_test.mbt
    python3 scripts/gen-fixtures.py --check   # exit 1 if the file is stale
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "svgo" / "plugins" / "fixtures"
UPSTREAM = FIXTURES / "upstream"
KNOWN = UPSTREAM / "KNOWN_FAILURES.txt"
OUT = ROOT / "svgo" / "plugins" / "fixtures_test.mbt"
SINGLE_PASS = {"addAttributesToSVGElement", "convertTransform"}

# Plugins from svgo's preset-default that svgo.mbt does not have yet. Their
# upstream cases are imported and generated as skipped tests, so the gap is
# visible in the test summary instead of only in the README. Delete an entry
# when the plugin lands; its cases go live and must pass (or be listed in
# KNOWN_FAILURES.txt with a reason).
NOT_IMPLEMENTED : dict[str, str] = {}


def multiline(text: str) -> str:
    lines = text.strip("\n").split("\n")
    return "(\n" + "\n".join("      #|" + l for l in lines) + "\n    )"


def known_failures() -> dict:
    out = {}
    if KNOWN.exists():
        for line in KNOWN.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            name, _, reason = line.partition("#")
            out[name.strip()] = reason.strip()
    return out


def own_case(path: pathlib.Path) -> str:
    plugin = path.name.split(".")[0]
    sections = [s.strip("\n") for s in path.read_text().split("\n@@@\n")]
    if len(sections) < 2:
        sys.exit(f"{path}: expected 'input @@@ expected'")
    params = json.loads(sections[2]) if len(sections) > 2 and sections[2].strip() else {}
    precision = int(params.get("precision", 3))
    multipass = "true" if params.get("multipass", False) else "false"
    return f'''
///|
test "fixture {path.stem}" {{
  check_fixture(
    "{plugin}",
    {multiline(sections[0])},
    {multiline(sections[1])},
    precision={precision},
    multipass={multipass},
    params={json.dumps(sections[2] if len(sections) > 2 and sections[2].strip() else "{}", ensure_ascii=False)},
  )
}}'''


def upstream_case(path: pathlib.Path, known: dict, stats: dict) -> str:
    plugin = path.name.split(".")[0]
    body = path.read_text()
    items = re.split(r"\s*===\s*", body)
    body = items[1] if len(items) == 2 else items[0]
    parts = re.split(r"\s*@@@\s*", body)
    if len(parts) < 2:
        sys.exit(f"{path}: expected 'input @@@ expected'")
    params = json.loads(parts[2]) if len(parts) > 2 and parts[2].strip() else {}
    precision = int(params.get("floatPrecision", 3))
    passes = 1 if plugin in SINGLE_PASS else 2
    name = path.stem
    attr = ""
    expect_fail = "false"
    if plugin in NOT_IMPLEMENTED:
        if name in known:
            sys.exit(
                f"{name}: {plugin} is unimplemented, so the case is skipped; "
                "remove it from KNOWN_FAILURES.txt"
            )
        stats["missing"] += 1
        attr = f'#skip("{NOT_IMPLEMENTED[plugin]}")\n'
    elif name in known:
        stats["known"] += 1
        expect_fail = "true"
    else:
        stats["passing"] += 1
    return f'''
///|
{attr}test "upstream {name}" {{
  check_fixture_upstream(
    "{plugin}",
    {multiline(parts[0])},
    {multiline(parts[1])},
    precision={precision},
    params={json.dumps(parts[2] if len(parts) > 2 and parts[2].strip() else "{}", ensure_ascii=False)},
    passes={passes},
    expect_fail={expect_fail},
  )
}}'''


def render() -> tuple[str, dict]:
    known = known_failures()
    stats = {"own": 0, "passing": 0, "known": 0, "skipped": 0, "missing": 0}
    parts = [
        "// Generated by scripts/gen-fixtures.py from svgo/plugins/fixtures/**/*.txt. DO NOT EDIT.",
        "// Regenerate with: python3 scripts/gen-fixtures.py",
    ]
    for path in sorted(FIXTURES.glob("*.txt")):
        parts.append(own_case(path))
        stats["own"] += 1
    seen = set()
    for path in sorted(UPSTREAM.glob("*.txt")):
        if path == KNOWN:
            continue
        seen.add(path.stem)
        parts.append(upstream_case(path, known, stats))
    stale = sorted(set(known) - seen)
    if stale:
        sys.exit(f"KNOWN_FAILURES.txt lists cases that do not exist: {', '.join(stale)}")
    return "\n".join(parts) + "\n", stats


def main() -> None:
    content, stats = render()
    summary = (
        f"own {stats['own']}, upstream passing {stats['passing']}, "
        f"known failures {stats['known']}, skipped (params) {stats['skipped']}, "
        f"skipped (plugin missing) {stats['missing']}"
    )
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale; run python3 scripts/gen-fixtures.py")
        print(f"{OUT.relative_to(ROOT)} is up to date ({summary})")
        return
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)} ({summary})")


if __name__ == "__main__":
    main()
